### ISSUE TITLE
Can't compile the SoftWire_MLX90614 example

### ISSUE THREAD

**Issue by mdanetzky** [stevemarple/SoftWire#1]
Line 72 is referencing a non-existent method (rawWrite):
```c
errors += i2c.rawWrite(command);
```
Changing it to:
```c
errors += i2c.write(command);
```
seems to have solved the issue.

**Comment by stevemarple** [comment]
Thanks, `rawWrite()` was renamed in 29776161178517a81da1b52ea0cc85d2193030f0 but the example was not changed.
