### ISSUE TITLE
configure SoftWire  and set up buffer

### ISSUE THREAD

**Issue by quangvu912** [stevemarple/SoftWire#12]
Hi stevemarple,
i want to use softWire  for 3 pressure sensors with same address (because i dont have multiplexer) so i try to use ur library. 
As u said high-level functions provide almost direct compatibility with the Wire library.
I dont know how to set up buffer,  con figure SoftWire to use beginTransmission(), endTransmission(), read(), write() and requestFrom () and other high-level functions. 
this is my code 
[softwire.txt](https://github.com/stevemarple/SoftWire/files/4535068/softwire.txt)

could you help me to it. Thank you so much

**Comment by stevemarple** [comment]
I have added a new example called `ReadDS1307` that shows how to configure the buffers.
