### ISSUE TITLE
Better documentation of run-time setting sda and scl pins

### ISSUE THREAD

**Issue by joesphan** [stevemarple/SoftWire#15]
Hello! Love your library Steve,
I was having trouble finding how to set sda pins and scl pins during runtime, I'm requesting this block of code be mentioned in the README:
```cpp
void SoftWire::setSda(uint8_t sda)
{
	_sda = sda;
}


void SoftWire::setScl(uint8_t scl)
{
	_scl = scl;
}
```

**Comment by stevemarple** [comment]
Thank you for mentioning this, I have updated the README.
