### ISSUE TITLE
Air001 sw.write() output is missing

### ISSUE THREAD

**Issue by createskyblue** [stevemarple/SoftWire#33]
![image](https://github.com/stevemarple/SoftWire/assets/20317561/f74ae5ce-2db6-4312-8600-b761ead39943)
![image](https://github.com/stevemarple/SoftWire/assets/20317561/5e1e8e61-87da-4c84-b979-a46f5181beda)

![image](https://github.com/stevemarple/SoftWire/assets/20317561/37d0194a-d5d7-4425-a3f1-cedc39029453)
The development board is air001
Arduino 2.0

Strangely， The logic analyzer found that write() is missing 🤔

**Comment by stevemarple** [comment]
The code appears to be from the [Adafruit_BMP280](https://github.com/adafruit/Adafruit_BMP280_Library) library. How is this relevant to the `SoftWire` library?
